app:
  desc: Gin框架学习实践
  version: v1.0.0
  addr: 0.0.0.0:8081
  env: dev
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  database: test
  charset: utf8mb4
  parsetime: true
redis:
  host: 127.0.0.1
  port: 6379
  password: 123456
  default: 1
  timeout: 5
jwt:
  secret: skyful
  issuer: 茅十八
  expire: 24h