definitions:
  controller.ArticleIn:
    properties:
      author:
        type: string
      cid:
        type: integer
      content:
        type: string
      cover:
        type: string
      title:
        type: string
    required:
    - author
    - cid
    - content
    - cover
    - title
    type: object
  controller.CategoryDto:
    properties:
      name:
        maxLength: 64
        minLength: 2
        type: string
    required:
    - name
    type: object
  controller.LoginDto:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  controller.UserDto:
    properties:
      avatar:
        type: string
      email:
        type: string
      password:
        type: string
      phone:
        type: string
      username:
        type: string
    required:
    - avatar
    - email
    - password
    - phone
    - username
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
      success:
        type: boolean
      timestamp:
        type: integer
    type: object
info:
  contact: {}
  description: 博客主要包含用户、文章和分类
  license:
    name: Apache 2.0
  title: Gin博客项目接口文档
  version: "1.0"
paths:
  /api/article/{id}/hot:
    get:
      consumes:
      - application/json
      description: 通过文章id将文章变为热门
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文章id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 将文章变为热门
      tags:
      - 文章接口
  /api/article/{id}/off:
    get:
      consumes:
      - application/json
      description: 通过文章id将文章上架
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文章id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 下架文章
      tags:
      - 文章接口
  /api/article/{id}/on:
    get:
      consumes:
      - application/json
      description: 通过文章id将文章上架
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文章id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 上架文章
      tags:
      - 文章接口
  /api/article/category/{id}:
    get:
      consumes:
      - application/json
      description: 通过参数分类id获取该id下的文章列表
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 分类id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 获取分类下的文章列表
      tags:
      - 文章接口
  /api/article/create:
    post:
      consumes:
      - application/json
      description: 创建文章，
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文章参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/controller.ArticleIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 创建文章
      tags:
      - 文章接口
  /api/article/delete/{id}:
    delete:
      consumes:
      - application/json
      description: 通过文章id删除指定的文章
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文章title
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 删除文章接口
      tags:
      - 文章接口
  /api/article/detail/{id}:
    get:
      consumes:
      - application/json
      description: 通过参数文章id获取文章的详情
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文章id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 获取文章详情
      tags:
      - 文章接口
  /api/article/list:
    get:
      consumes:
      - application/json
      description: 默认获取全部文章列表，分页参数为page_num和page_size
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 当前第X页
        in: query
        name: page_num
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 获取文章列表
      tags:
      - 文章接口
  /api/article/search:
    get:
      consumes:
      - application/json
      description: 条件筛选文章列表，如title、status
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文章名称
        in: query
        name: title
        type: string
      - description: 文章内容
        in: query
        name: content
        type: string
      - description: 文章状态
        in: query
        name: status
        type: integer
      - description: 文章热门
        in: query
        name: is_hot
        type: integer
      - description: 文章分类
        in: query
        name: cid
        type: integer
      - description: 当前第X页
        in: query
        name: page_num
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 筛选文章接口
      tags:
      - 文章接口
  /api/article/update/{id}:
    put:
      consumes:
      - application/json
      description: 通过文章id更新文章详细信息
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文章id
        in: path
        name: id
        required: true
        type: integer
      - description: 文章参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/controller.ArticleIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 更新文章详情
      tags:
      - 文章接口
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: 用户登录，返回token
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 登录参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/controller.LoginDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 用户登录
      tags:
      - 用户接口
  /api/category/create:
    post:
      consumes:
      - application/json
      description: 添加分类，参数为分类name
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 分类参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/controller.CategoryDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 添加分类
      tags:
      - 分类接口
  /api/category/delete/{id}:
    delete:
      consumes:
      - application/json
      description: 通过分类id删除分类
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 分类id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 删除分类
      tags:
      - 分类接口
  /api/category/detail/{id}:
    get:
      consumes:
      - application/json
      description: 通过分类id获取分类详情信息
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 分类id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 获取分类详情
      tags:
      - 分类接口
  /api/category/disable/{id}:
    get:
      consumes:
      - application/json
      description: 通过分类id禁用分类
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 分类id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 禁用分类
      tags:
      - 分类接口
  /api/category/enable/{id}:
    get:
      consumes:
      - application/json
      description: 通过分类id激活分类
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 分类id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 激活分类
      tags:
      - 分类接口
  /api/category/list:
    get:
      consumes:
      - application/json
      description: 默认获取全部分类列表，分页参数为page_num和page_size
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 当前第X页
        in: query
        name: page_num
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 获取分类列表
      tags:
      - 分类接口
  /api/category/search:
    get:
      consumes:
      - application/json
      description: 通过分类name搜索分类列表
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 分类name
        in: query
        name: title
        type: string
      - description: 当前第X页
        in: query
        name: page_num
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 搜索分类
      tags:
      - 分类接口
  /api/category/update/{id}:
    put:
      consumes:
      - application/json
      description: 更新分类，通过分类id找到分类并更新
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 分类id
        in: path
        name: id
        required: true
        type: integer
      - description: 分类参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/controller.CategoryDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 更新分类
      tags:
      - 分类接口
  /api/user/create:
    post:
      consumes:
      - application/json
      description: 添加用户，参数为username和password
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/controller.UserDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 添加用户
      tags:
      - 用户接口
  /api/user/delete/{id}:
    delete:
      consumes:
      - application/json
      description: 通过用户id删除用户
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 删除用户
      tags:
      - 用户接口
  /api/user/detail/{id}:
    get:
      consumes:
      - application/json
      description: 通过用户id获取用户详情
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 获取用户详情页
      tags:
      - 用户接口
  /api/user/enable/{id}:
    get:
      consumes:
      - application/json
      description: 通过用户id禁用用户
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 激活用户
      tags:
      - 用户接口
  /api/user/list:
    get:
      consumes:
      - application/json
      description: 通过用户username获取用户列表数据
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户username
        in: query
        name: username
        type: string
      - description: 当前第X页
        in: query
        name: page_num
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 搜索用户列表
      tags:
      - 用户接口
  /api/user/reset/{id}:
    get:
      consumes:
      - application/json
      description: 通过用户id重置登录密码为123456
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 重置密码
      tags:
      - 用户接口
swagger: "2.0"
